# MSB LOR folder-alignment launcher for Windows
#
# Purpose:
#   Run the current read-only Google Shared Drive Folder Alignment reports
#   from the repository root and open the HTML reports generated by this run.
#
# Optional environment variables:
#   MSB_FOLDER_ALIGNMENT_DB
#   MSB_FOLDER_ALIGNMENT_DRIVE_ROOT
#   MSB_FOLDER_ALIGNMENT_OUTPUT_DIR

$ErrorActionPreference = 'Stop'

$RepoRoot = $PSScriptRoot
$AlignmentScript = Join-Path $RepoRoot 'Docs\01_LOR_System\02_Data_Extraction\Folder_Alignment\folder_alignment.py'

if (-not (Test-Path -LiteralPath $AlignmentScript -PathType Leaf)) {
    Write-Error "Folder Alignment script not found: $AlignmentScript"
    exit 2
}

$PythonCommand = Get-Command python -ErrorAction SilentlyContinue
if (-not $PythonCommand) {
    $PythonCommand = Get-Command python3 -ErrorAction SilentlyContinue
}
if (-not $PythonCommand) {
    Write-Error "Python 3 was not found in the current PowerShell environment."
    exit 3
}

$PythonArgs = @()

if ($env:MSB_FOLDER_ALIGNMENT_DB) {
    $PythonArgs += @('--db', $env:MSB_FOLDER_ALIGNMENT_DB)
}

if ($env:MSB_FOLDER_ALIGNMENT_DRIVE_ROOT) {
    $PythonArgs += @('--drive-root', $env:MSB_FOLDER_ALIGNMENT_DRIVE_ROOT)
}

if ($env:MSB_FOLDER_ALIGNMENT_OUTPUT_DIR) {
    $PythonArgs += @('--output-dir', $env:MSB_FOLDER_ALIGNMENT_OUTPUT_DIR)
}

Write-Host "[INFO] Folder Alignment: $AlignmentScript"
Write-Host "[INFO] Python: $($PythonCommand.Source)"

$RunOutput = [System.Collections.Generic.List[string]]::new()

& $PythonCommand.Source $AlignmentScript @PythonArgs @args 2>&1 |
ForEach-Object {
    $Line = [string]$_
    $RunOutput.Add($Line)
    Write-Host $Line
}

$AlignmentExitCode = $LASTEXITCODE
if ($null -eq $AlignmentExitCode) {
    $AlignmentExitCode = 0
}

if ($AlignmentExitCode -ne 0) {
    exit $AlignmentExitCode
}

$HtmlPaths = [System.Collections.Generic.List[string]]::new()

foreach ($Line in $RunOutput) {
    if ($Line -match '^\[INFO\] (?:HTML|Procedure Inventory HTML):\s+(.+\.html)\s*$') {
        $Candidate = $Matches[1].Trim()
        if (-not $HtmlPaths.Contains($Candidate)) {
            $HtmlPaths.Add($Candidate)
        }
    }
}

if ($HtmlPaths.Count -eq 0) {
    Write-Warning "Folder Alignment completed, but no generated HTML report path was returned."
    exit 0
}

foreach ($HtmlPath in $HtmlPaths) {
    if (Test-Path -LiteralPath $HtmlPath -PathType Leaf) {
        Write-Host "[INFO] Opening HTML report: $HtmlPath"
        Start-Process $HtmlPath
    }
    else {
        Write-Warning "Generated HTML report was not found: $HtmlPath"
    }
}

exit 0
