/* ======================================================================
   Create ref.label_template

   Status: REVIEWED CANDIDATE — NOT YET APPLIED TO PRODUCTION
   Subsystem: Labeling and Scanning
   Purpose:
     Define the governed label format selected by Production Database
     records/workflows without storing the PRINT-SERVER installation root
     or Windows printer queue on the source asset.

   IMPORTANT:
     - This creates a NEW production table only.
     - It does NOT alter ref.display.
     - Existing production dependencies are verified before DDL runs.
     - Do not add ref.display.label_template_id until the live ref.display
       schema, triggers, permissions, and Directus metadata are inspected.

   Runtime path contract:
     config.local.ini on PRINT-SERVER owns the machine-local template root:
       C:\MSB_LabelService\templates

     ref.label_template.template_relative_path stores only the path below
     that root, using forward slashes for portability, for example:
       pt_p950nw/QR_display_labels_2_line_24mm.lbx
   ====================================================================== */

BEGIN;

/* ----------------------------------------------------------------------
   Verify current production dependencies rather than assuming repository
   DDL still matches the live database.
   ---------------------------------------------------------------------- */
DO $$
BEGIN
    IF to_regnamespace('ref') IS NULL THEN
        RAISE EXCEPTION 'Required schema ref does not exist';
    END IF;

    IF to_regprocedure('ref.set_actor_on_insert()') IS NULL THEN
        RAISE EXCEPTION 'Required trigger function ref.set_actor_on_insert() does not exist';
    END IF;

    IF to_regprocedure('ref.set_updated_fields()') IS NULL THEN
        RAISE EXCEPTION 'Required trigger function ref.set_updated_fields() does not exist';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'msbadmin') THEN
        RAISE EXCEPTION 'Required owner role msbadmin does not exist';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'directus_app') THEN
        RAISE EXCEPTION 'Required application role directus_app does not exist';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'printservice') THEN
        RAISE EXCEPTION 'Required service role printservice does not exist';
    END IF;

    IF to_regclass('ref.label_template') IS NOT NULL THEN
        RAISE EXCEPTION 'ref.label_template already exists; stop and inspect the live object before proceeding';
    END IF;
END
$$;

CREATE TABLE ref.label_template (
    label_template_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label_template_code text NOT NULL UNIQUE,
    label_template_name text NOT NULL,
    label_class text NOT NULL,
    media_width_mm smallint,
    media_type text NOT NULL,
    template_relative_path text NOT NULL UNIQUE,
    description text,
    active_flag boolean NOT NULL DEFAULT true,

    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by text NOT NULL DEFAULT CURRENT_USER,
    created_by_person_id bigint,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_by text NOT NULL DEFAULT CURRENT_USER,
    updated_by_person_id bigint,

    CONSTRAINT ck_label_template_code_not_blank
        CHECK (btrim(label_template_code) <> ''),
    CONSTRAINT ck_label_template_name_not_blank
        CHECK (btrim(label_template_name) <> ''),
    CONSTRAINT ck_label_template_class_not_blank
        CHECK (btrim(label_class) <> ''),
    CONSTRAINT ck_label_template_media_type_not_blank
        CHECK (btrim(media_type) <> ''),
    CONSTRAINT ck_label_template_media_width_positive
        CHECK (media_width_mm IS NULL OR media_width_mm > 0),
    CONSTRAINT ck_label_template_relative_path_not_blank
        CHECK (btrim(template_relative_path) <> ''),
    CONSTRAINT ck_label_template_relative_path_not_windows_absolute
        CHECK (template_relative_path !~ '^[A-Za-z]:[\\/]' AND template_relative_path !~ '^[/\\]{2}')
);

ALTER TABLE ref.label_template OWNER TO msbadmin;

COMMENT ON TABLE ref.label_template IS
'Governed logical/physical label format lookup. Stores the label format, media requirement, and template path relative to the PRINT-SERVER configured template root. Does not store the PRINT-SERVER installation root or Windows printer queue.';

COMMENT ON COLUMN ref.label_template.label_template_code IS
'Stable machine-facing code used by database and LabelPrintService integration, for example DISPLAY_36MM.';

COMMENT ON COLUMN ref.label_template.label_template_name IS
'Human-readable label-template name suitable for administration and Directus relationship display.';

COMMENT ON COLUMN ref.label_template.label_class IS
'Label purpose/class such as DISPLAY, CONTAINER, LOCATION, or WIRING. Initial installed rows are Display only.';

COMMENT ON COLUMN ref.label_template.media_width_mm IS
'Nominal required media width in millimeters when width is meaningful. NULL is allowed for future media where another dimensioning scheme is more appropriate.';

COMMENT ON COLUMN ref.label_template.media_type IS
'Governed media family/description code, for example LAMINATED_TAPE. Operators do not select printers from this table.';

COMMENT ON COLUMN ref.label_template.template_relative_path IS
'Path to the current LBX implementation relative to the LabelPrintService template_dir root. Store forward-slash relative paths only; do not store C:\MSB_LabelService or a UNC share here.';

CREATE TRIGGER trg_label_template_set_actor_insert
BEFORE INSERT ON ref.label_template
FOR EACH ROW
EXECUTE FUNCTION ref.set_actor_on_insert();

CREATE TRIGGER trg_label_template_set_updated
BEFORE UPDATE ON ref.label_template
FOR EACH ROW
EXECUTE FUNCTION ref.set_updated_fields();

/* ----------------------------------------------------------------------
   Initial approved Display formats.
   Existing Displays are NOT altered by this script.
   ---------------------------------------------------------------------- */
INSERT INTO ref.label_template (
    label_template_code,
    label_template_name,
    label_class,
    media_width_mm,
    media_type,
    template_relative_path,
    description
)
VALUES
(
    'DISPLAY_36MM',
    'Display Label - 36 mm',
    'DISPLAY',
    36,
    'LAMINATED_TAPE',
    'pt_p950nw/QR_display_labels_2_line_36mm.lbx',
    'Current standard Display identity label using 36 mm laminated P-touch media.'
),
(
    'DISPLAY_24MM',
    'Display Label - 24 mm',
    'DISPLAY',
    24,
    'LAMINATED_TAPE',
    'pt_p950nw/QR_display_labels_2_line_24mm.lbx',
    'Narrow Display identity label using 24 mm laminated P-touch media.'
);

/* Directus needs read access for relationship display; LabelPrintService
   needs read access for runtime resolution. Template maintenance remains a
   controlled administrator/database action in this phase. */
GRANT SELECT ON TABLE ref.label_template TO directus_app;
GRANT SELECT ON TABLE ref.label_template TO printservice;

COMMIT;

/* ----------------------------------------------------------------------
   Post-install verification — run after COMMIT.
   ---------------------------------------------------------------------- */
SELECT
    label_template_id,
    label_template_code,
    label_template_name,
    label_class,
    media_width_mm,
    media_type,
    template_relative_path,
    active_flag,
    created_at,
    created_by,
    created_by_person_id,
    updated_at,
    updated_by,
    updated_by_person_id
FROM ref.label_template
ORDER BY label_template_id;
