create table if not exists ref.inventory_type (
    inventory_type_id integer generated by default as identity primary key,

    inventory_type_name text not null unique,
    description text not null,

    created_at timestamptz not null default now(),
    created_by text        not null default current_user,
    updated_at timestamptz not null default now(),
    updated_by text        not null default current_user
);

create trigger trg_inventory_type_set_updated
before update on ref.inventory_type
for each row
execute function ref.set_updated_fields();