create table if not exists ref.pallet_type (
    pallet_type_id integer generated by default as identity primary key,
    pallet_type_name text not null unique,
    notes text null,

    created_at timestamptz not null default now(),
    created_by text        not null default current_user,
    updated_at timestamptz not null default now(),
    updated_by text        not null default current_user
);

drop trigger if exists trg_touch_pallet_type on ref.pallet_type;
create trigger trg_touch_pallet_type
before update on ref.pallet_type
for each row
execute function ref.tg_touch_row();